
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const INCREMENT = 'INCREMENT';
export const FILTER_DATE_RANGE = 'FILTER_DATE_RANGE';
export const FILTER_SELECT = 'FILTER_SELECT';
export const ADD_COMMENT = 'ADD_COMMENT';